version: '3.9'

services:
  bot:
    build: .
    command: ["bash", "start_external_db.sh"]
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      # Настройки внешней БД
      USE_EXTERNAL_DB: true
      EXTERNAL_DB_HOST: ${EXTERNAL_DB_HOST}
      EXTERNAL_DB_PORT: ${EXTERNAL_DB_PORT:-5432}
      EXTERNAL_DB_NAME: ${EXTERNAL_DB_NAME}
      EXTERNAL_DB_USER: ${EXTERNAL_DB_USER}
      EXTERNAL_DB_PASSWORD: ${EXTERNAL_DB_PASSWORD}
      EXTERNAL_DB_SSL: ${EXTERNAL_DB_SSL:-false}
      # Остальные настройки
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
      ADMIN_USER_ID: ${ADMIN_USER_ID}
      GENERAL_CHAT_ID: ${GENERAL_CHAT_ID:-0}
      ADMIN_LOG_CHAT_ID: ${ADMIN_LOG_CHAT_ID:-0}
      THREAD_WORK_TIME: ${THREAD_WORK_TIME:-0}
      THREAD_LK_PROCESSING: ${THREAD_LK_PROCESSING:-0}
      THREAD_LK_PROBLEM: ${THREAD_LK_PROBLEM:-0}
      THREAD_EPGU_ACCEPTED: ${THREAD_EPGU_ACCEPTED:-0}
      THREAD_EPGU_MAIL_QUEUE: ${THREAD_EPGU_MAIL_QUEUE:-0}
      THREAD_EPGU_PROBLEM: ${THREAD_EPGU_PROBLEM:-0}
      THREAD_MAIL_CONFIRMED: ${THREAD_MAIL_CONFIRMED:-0}
      THREAD_MAIL_REJECTED: ${THREAD_MAIL_REJECTED:-0}
      THREAD_PROBLEM_SOLVED: ${THREAD_PROBLEM_SOLVED:-0}
      THREAD_PROBLEM_SOLVED_QUEUE: ${THREAD_PROBLEM_SOLVED_QUEUE:-0}
      THREAD_PROBLEM_IN_PROGRESS: ${THREAD_PROBLEM_IN_PROGRESS:-0}
      THREAD_QUEUE_UPDATED: ${THREAD_QUEUE_UPDATED:-0}
      THREAD_ESCALATION: ${THREAD_ESCALATION:-0}
    restart: always
    volumes:
      - .:/app 